package myclass;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://www.daml.org/2001/01/gedcom/gedcom 
 * @author Auto-generated by schemagen on 12 Sep 2012 14:22 
 */
public class Gedcom {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.daml.org/2001/01/gedcom/gedcom#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource birth = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#birth" );
    
    public static final Resource childIn = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#childIn" );
    
    public static final Resource date = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#date" );
    
    public static final Resource death = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#death" );
    
    public static final Resource divorce = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#divorce" );
    
    public static final Resource eventProperty = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#eventProperty" );
    
    public static final Resource familyEventProperty = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#familyEventProperty" );
    
    public static final Resource givenName = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#givenName" );
    
    public static final Resource individualEventProperty = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#individualEventProperty" );
    
    public static final Resource marriage = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#marriage" );
    
    public static final Resource name = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#name" );
    
    public static final Resource place = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#place" );
    
    public static final Resource sex = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#sex" );
    
    public static final Resource spouseIn = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#spouseIn" );
    
    public static final Resource surname = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#surname" );
    
    public static final Resource title = m_model.createResource( "http://www.daml.org/2001/01/gedcom/gedcom#title" );
    
}
