package myclass;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://www.w3.org/2002/12/cal/ical 
 * @author Auto-generated by schemagen on 29 Sep 2012 22:56 
 */
public class Ical {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2002/12/cal/ical#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource DomainOf_rrule = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#DomainOf_rrule" );
    
    public static final Resource List_of_Float = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#List_of_Float" );
    
    /** <p>Provide a grouping of component properties that define an alarm.</p> */
    public static final Resource Valarm = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Valarm" );
    
    public static final Resource Value_CAL_ADDRESS = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_CAL-ADDRESS" );
    
    public static final Resource Value_DATE = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_DATE" );
    
    public static final Resource Value_DATE_TIME = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_DATE-TIME" );
    
    public static final Resource Value_DURATION = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_DURATION" );
    
    public static final Resource Value_PERIOD = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_PERIOD" );
    
    public static final Resource Value_RECUR = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Value_RECUR" );
    
    /** <p>Provide a grouping of component properties that describe an event.</p> */
    public static final Resource Vevent = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Vevent" );
    
    /** <p>Provide a grouping of component properties that describe either a request 
     *  for free/busy time, describe a response to a request for free/busy time or 
     *  describe a published set of busy time.</p>
     */
    public static final Resource Vfreebusy = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Vfreebusy" );
    
    /** <p>Provide a grouping of component properties that describe a journal entry.</p> */
    public static final Resource Vjournal = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Vjournal" );
    
    /** <p>Provide a grouping of component properties that defines a time zone.</p> */
    public static final Resource Vtimezone = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Vtimezone" );
    
    /** <p>Provide a grouping of calendar properties that describe a to-do.</p> */
    public static final Resource Vtodo = m_model.createResource( "http://www.w3.org/2002/12/cal/ical#Vtodo" );
    
}
