package myclass;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://www.mindswap.org/~glapizco/technical.owl 
 * @author Auto-generated by schemagen on 19 Jul 2012 17:46 
 */
public class Technical {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mindswap.org/~glapizco/technical.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource DepictedThing = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#DepictedThing" );
    
    /** <p>The class of images</p> */
    public static final Resource Image = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#Image" );
    
    /** <p>2D spatial regions of an image or video frame</p> */
    public static final Resource ImagePart = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#ImagePart" );
    
    /** <p>Spatial regions of an image or video frame that correspond to text or captions</p> */
    public static final Resource ImageText = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#ImageText" );
    
    /** <p>Mosaic or panaoramic view of a video segment</p> */
    public static final Resource Mosaic = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#Mosaic" );
    
    /** <p>2D spatio-temporal regions of video data</p> */
    public static final Resource MovingRegion = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#MovingRegion" );
    
    /** <p>The class of multimedia resources</p> */
    public static final Resource Multimedia = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#Multimedia" );
    
    /** <p>The class of multimedia data</p> */
    public static final Resource MultimediaContent = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#MultimediaContent" );
    
    /** <p>The class of fragments of multimedia content</p> */
    public static final Resource Segment = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#Segment" );
    
    /** <p>2D spatial regions of an image or video frame</p> */
    public static final Resource StillRegion = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#StillRegion" );
    
    /** <p>The class of videos</p> */
    public static final Resource Video = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#Video" );
    
    /** <p>Frame of a video</p> */
    public static final Resource VideoFrame = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#VideoFrame" );
    
    /** <p>Temporal intervals or segments of video data</p> */
    public static final Resource VideoSegment = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#VideoSegment" );
    
    public static final Resource VideoSegmentsOrStillRegions = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#VideoSegmentsOrStillRegions" );
    
    /** <p>Spatio-temporal regions of video data that correspond to text or captions</p> */
    public static final Resource VideoText = m_model.createResource( "http://www.mindswap.org/~glapizco/technical.owl#VideoText" );
    
}
