/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iannotate.gui;

import iannotate.database.DbInterface;
import iannotate.database.SqlQuery;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sameer
 */
public class SignUp extends javax.swing.JFrame {
    
    static public LogInForm log = new LogInForm();
    //static public MainFrame mainF = new MainFrame();
    static public SignUp sign = new SignUp();
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        userNameLabel = new javax.swing.JLabel();
        passWordLabel = new javax.swing.JLabel();
        rePassLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        rePass = new javax.swing.JPasswordField();
        dob = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        sexLabel = new javax.swing.JLabel();
        passErrorLabel = new javax.swing.JLabel();
        userErrorLabel = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        executeLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setText("username :");
        userNameLabel.setBounds(0, 40, 100, 30);
        jLayeredPane1.add(userNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passWordLabel.setText("password :");
        passWordLabel.setBounds(0, 80, 100, 30);
        jLayeredPane1.add(passWordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        rePassLabel.setText("re-enter password :");
        rePassLabel.setBounds(0, 120, 150, 30);
        jLayeredPane1.add(rePassLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dobLabel.setText("date of birth :");
        dobLabel.setBounds(0, 160, 100, 30);
        jLayeredPane1.add(dobLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contactLabel.setText("contact :");
        contactLabel.setBounds(0, 200, 100, 30);
        jLayeredPane1.add(contactLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addressLabel.setText("address :");
        addressLabel.setBounds(0, 240, 100, 30);
        jLayeredPane1.add(addressLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userName.setBounds(130, 40, 140, 30);
        jLayeredPane1.add(userName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userName.getAccessibleContext().setAccessibleName("");

        passWord.setBounds(130, 80, 140, 30);
        jLayeredPane1.add(passWord, javax.swing.JLayeredPane.DEFAULT_LAYER);
        rePass.setBounds(130, 120, 140, 30);
        jLayeredPane1.add(rePass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dob.setBounds(130, 160, 140, 30);
        jLayeredPane1.add(dob, javax.swing.JLayeredPane.DEFAULT_LAYER);
        contact.setBounds(130, 200, 140, 30);
        jLayeredPane1.add(contact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        address.setBounds(130, 240, 140, 30);
        jLayeredPane1.add(address, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(MaleRadioButton);
        MaleRadioButton.setText("Male");
        MaleRadioButton.setBounds(100, 280, 80, 30);
        jLayeredPane1.add(MaleRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setBounds(190, 280, 70, 30);
        jLayeredPane1.add(FemaleRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sexLabel.setText("sex:");
        sexLabel.setBounds(0, 280, 100, 30);
        jLayeredPane1.add(sexLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        passErrorLabel.setBounds(280, 120, 220, 30);
        jLayeredPane1.add(passErrorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        userErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        userErrorLabel.setBounds(270, 40, 220, 30);
        jLayeredPane1.add(userErrorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        doneButton.setVisible(false);
        doneButton.setText("Finish");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(save)
                        .addGap(27, 27, 27)
                        .addComponent(executeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doneButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(executeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
         DbInterface[] db = new DbInterface[2];
         db[0] = new SqlQuery("major_project");
         
         
         String sex;
         
         
         String user = userName.getText().toString().toLowerCase().trim();
        try {
            if( user.contentEquals(db[0].fetch().getString(2))){
                      userErrorLabel.setText("*"+user + " is already taken");
                       
            }
//            else
//                 db[] = new SqlQuery("major_project");
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         char[] pass = passWord.getPassword();
         String passString = String.valueOf(pass);
         char[] rePass1 = rePass.getPassword();
         String rePass1String = String.valueOf(rePass1);
         
         if(!passString.equals(rePass1String))
         {   passErrorLabel.setText("password do not match");
             System.out.println("pass check");
         }
         
         if(MaleRadioButton.isSelected())             
             sex = "male";
         else
             sex = "female";
         
         double num = Double.valueOf(contact.getText().toString());
         String addr = address.getText().toString();
         String date = dob.getText().toString();
         
         
       boolean r = false;
             
        try {
            
                     
            if( !( user.contentEquals( db[0].fetch().getString(2) ) ) ) 
            {   if(passString.equals(rePass1String))
                r = db[0].insertInto( user, passString, sex, num, addr, date);
                executeLabel.setText("Congratulations your acoount has been created");
                new File(user).mkdir();
                doneButton.setVisible(true);
            }
        }//end try
        catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch
       
    
         
             
 ////        
    }//GEN-LAST:event_saveActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        
        sign.setVisible(false);
        sign.dispose();
//        log.setVisible(true);
        log.main(null);
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                sign.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel executeLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel passErrorLabel;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JLabel passWordLabel;
    private javax.swing.JPasswordField rePass;
    private javax.swing.JLabel rePassLabel;
    private javax.swing.JButton save;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel userErrorLabel;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
